// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApoUw7ELUmXvO5qM-5bRQZlFApLW85eTY',
    appId: '1:774891061548:web:2e965aade8e02886d6ec89',
    messagingSenderId: '774891061548',
    projectId: 'fluttermessaging-4a3e1',
    authDomain: 'fluttermessaging-4a3e1.firebaseapp.com',
    storageBucket: 'fluttermessaging-4a3e1.appspot.com',
    measurementId: 'G-GS00XQQ5FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfTYHQhJkHe_-mCJ0R_Dq9Qj1s5IS38w4',
    appId: '1:774891061548:android:c80d8714c4770df8d6ec89',
    messagingSenderId: '774891061548',
    projectId: 'fluttermessaging-4a3e1',
    storageBucket: 'fluttermessaging-4a3e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAf781bl1k7mTW5ncsZBxUsZvkp-s5elc',
    appId: '1:774891061548:ios:8013e2e11b687f30d6ec89',
    messagingSenderId: '774891061548',
    projectId: 'fluttermessaging-4a3e1',
    storageBucket: 'fluttermessaging-4a3e1.appspot.com',
    iosBundleId: 'com.milap.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAf781bl1k7mTW5ncsZBxUsZvkp-s5elc',
    appId: '1:774891061548:ios:8013e2e11b687f30d6ec89',
    messagingSenderId: '774891061548',
    projectId: 'fluttermessaging-4a3e1',
    storageBucket: 'fluttermessaging-4a3e1.appspot.com',
    iosBundleId: 'com.milap.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApoUw7ELUmXvO5qM-5bRQZlFApLW85eTY',
    appId: '1:774891061548:web:7bc99c462712bd88d6ec89',
    messagingSenderId: '774891061548',
    projectId: 'fluttermessaging-4a3e1',
    authDomain: 'fluttermessaging-4a3e1.firebaseapp.com',
    storageBucket: 'fluttermessaging-4a3e1.appspot.com',
    measurementId: 'G-0B9DN148CC',
  );
}
